<#
.SYNOPSIS
    Builds the EPDesk Old User Data Uploader MSI.

.DESCRIPTION
    Publishes the app and packages it with WiX. By default the .NET runtime is
    bundled, so the MSI installs on a machine with nothing else on it. Pass
    -FrameworkDependent for a small MSI that instead requires the .NET Desktop
    Runtime 8 to already be present.

    Requires the WiX 4 CLI and its UI extension:

        dotnet tool install --global wix --version 4.0.5
        wix extension add -g WixToolset.UI.wixext/4.0.5

.EXAMPLE
    .\build-msi.ps1
    Self-contained MSI, roughly 60 MB, no prerequisites.

.EXAMPLE
    .\build-msi.ps1 -FrameworkDependent
    Small MSI that needs the .NET Desktop Runtime 8 on the target machine.
#>
[CmdletBinding()]
param(
    [string]$Configuration = 'Release',
    [ValidateSet('x64', 'x86', 'arm64')]
    [string]$Architecture = 'x64',
    [switch]$FrameworkDependent,
    [string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'

$installerDirectory = $PSScriptRoot
$projectDirectory = Split-Path -Parent $installerDirectory
$projectFile = Join-Path $projectDirectory 'EPDeskOldDataUploader.csproj'

if (-not $OutputDirectory) {
    $OutputDirectory = Join-Path $projectDirectory 'bin\msi'
}

$selfContained = -not $FrameworkDependent
$runtimeIdentifier = "win-$Architecture"
$publishDirectory = Join-Path $projectDirectory (
    "bin\publish-msi-$runtimeIdentifier-" + $(if ($selfContained) { 'sc' } else { 'fd' })
)

function Get-ProductVersion {
    $content = Get-Content -LiteralPath $projectFile -Raw

    if ($content -match '<Version>([^<]+)</Version>') {
        return $Matches[1].Trim()
    }

    return '1.0.0'
}

<#
.SYNOPSIS
    Writes a WiX fragment listing every published file as its own component.

.DESCRIPTION
    WiX 4 has no directory harvester of its own, so the component list is built
    here. Ids are plain counters over a sorted walk, which keeps them identical
    between builds; the component GUIDs are left as "*" so WiX derives each one
    from its install path and upgrades stay coherent.
#>
function Write-FilesFragment {
    param(
        [Parameter(Mandatory)][string]$SourceDirectory,
        [Parameter(Mandatory)][string]$DestinationFile
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $components = [System.Collections.Generic.List[string]]::new()
    $directories = [System.Collections.Generic.List[string]]::new()
    $script:fileIndex = 0

    function Add-Directory {
        param([string]$Path, [string]$DirectoryId, [int]$Depth)

        $indent = ' ' * (6 + ($Depth * 2))

        foreach ($file in Get-ChildItem -LiteralPath $Path -File | Sort-Object Name) {
            $script:fileIndex++
            $id = 'f{0}' -f $script:fileIndex
            $source = [System.Security.SecurityElement]::Escape($file.FullName)

            $components.Add("    <Component Directory=""$DirectoryId"" Guid=""*"">")
            $components.Add("      <File Id=""$id"" Source=""$source"" KeyPath=""yes"" />")
            $components.Add('    </Component>')
        }

        foreach ($child in Get-ChildItem -LiteralPath $Path -Directory | Sort-Object Name) {
            $script:fileIndex++
            $childId = 'd{0}' -f $script:fileIndex
            $name = [System.Security.SecurityElement]::Escape($child.Name)

            $directories.Add("$indent<Directory Id=""$childId"" Name=""$name"">")
            Add-Directory -Path $child.FullName -DirectoryId $childId -Depth ($Depth + 1)
            $directories.Add("$indent</Directory>")
        }
    }

    Add-Directory -Path $SourceDirectory -DirectoryId 'INSTALLFOLDER' -Depth 0

    $lines.Add('<?xml version="1.0" encoding="utf-8"?>')
    $lines.Add('<!-- Generated by build-msi.ps1. Do not edit. -->')
    $lines.Add('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
    $lines.Add('  <Fragment>')

    if ($directories.Count -gt 0) {
        $lines.Add('    <DirectoryRef Id="INSTALLFOLDER">')
        $lines.AddRange($directories)
        $lines.Add('    </DirectoryRef>')
    }

    $lines.Add('  </Fragment>')
    $lines.Add('  <Fragment>')
    $lines.Add('    <ComponentGroup Id="ApplicationFiles">')
    $lines.AddRange($components)
    $lines.Add('    </ComponentGroup>')
    $lines.Add('  </Fragment>')
    $lines.Add('</Wix>')

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $DestinationFile) | Out-Null
    Set-Content -LiteralPath $DestinationFile -Value $lines -Encoding utf8

    return ($components.Count / 3)
}

if (-not (Get-Command wix -ErrorAction SilentlyContinue)) {
    throw 'The WiX CLI was not found. Run: dotnet tool install --global wix --version 4.0.5'
}

$version = Get-ProductVersion
Write-Host "Building EPDesk Old User Data Uploader $version ($runtimeIdentifier, " -NoNewline
Write-Host $(if ($selfContained) { 'self-contained)' } else { 'framework-dependent)' })

# A stale publish folder would be harvested into the MSI along with the new one.
if (Test-Path -LiteralPath $publishDirectory) {
    Remove-Item -LiteralPath $publishDirectory -Recurse -Force
}

Write-Host 'Publishing...'
dotnet publish $projectFile `
    -c $Configuration `
    -r $runtimeIdentifier `
    --self-contained $selfContained.ToString().ToLower() `
    -o $publishDirectory `
    -v quiet `
    --nologo

if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE."
}

# The PDB is debugging weight nobody installing this will use.
Get-ChildItem -LiteralPath $publishDirectory -Filter *.pdb -Recurse |
    Remove-Item -Force

$published = Get-ChildItem -LiteralPath $publishDirectory -Recurse -File |
    Measure-Object -Property Length -Sum
Write-Host ("  {0} files, {1:N1} MB" -f $published.Count, ($published.Sum / 1MB))

$filesFragment = Join-Path $projectDirectory 'obj\Installer\Files.wxs'
$componentCount = Write-FilesFragment -SourceDirectory $publishDirectory `
    -DestinationFile $filesFragment
Write-Host "  $componentCount components generated"

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$suffix = if ($selfContained) { '' } else { '-framework-dependent' }
$msiPath = Join-Path $OutputDirectory `
    "EPDeskOldDataUploader-$version-$Architecture$suffix.msi"

Write-Host 'Packaging...'
wix build (Join-Path $installerDirectory 'Package.wxs') $filesFragment `
    -arch $Architecture `
    -d "PublishDir=$publishDirectory" `
    -d "ProductVersion=$version" `
    -ext WixToolset.UI.wixext `
    -bindpath $installerDirectory `
    -out $msiPath

if ($LASTEXITCODE -ne 0) {
    throw "wix build failed with exit code $LASTEXITCODE."
}

# ICE38, ICE43 and ICE57 all fire on the Start Menu shortcut because validation
# runs without knowing the package sets ALLUSERS=1. With Scope="perMachine" the
# shortcut lands in the all-users Start Menu, which is per-machine data, so the
# HKLM key path it is paired with is right and these three are false positives.
# Everything else is still checked.
Write-Host 'Validating...'
wix msi validate $msiPath -sice ICE38 -sice ICE43 -sice ICE57

if ($LASTEXITCODE -ne 0) {
    throw "MSI validation failed with exit code $LASTEXITCODE."
}

$msi = Get-Item -LiteralPath $msiPath
Write-Host ''
Write-Host ("MSI: {0}" -f $msi.FullName) -ForegroundColor Green
Write-Host ("Size: {0:N1} MB" -f ($msi.Length / 1MB))
Write-Host ''
Write-Host 'Install:   msiexec /i "' -NoNewline
Write-Host $msi.FullName -NoNewline
Write-Host '"'
Write-Host 'Silent:    msiexec /i "' -NoNewline
Write-Host $msi.FullName -NoNewline
Write-Host '" /qn'
Write-Host 'Uninstall: msiexec /x "' -NoNewline
Write-Host $msi.FullName -NoNewline
Write-Host '"'
