<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\EPDeskExtractionWorker\Services\Extraction\*.cs"
             Link="Services\Extraction\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
