<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.11</Version>
    <AssemblyVersion>1.0.11</AssemblyVersion>
    <FileVersion>1.0.11</FileVersion>
    <InformationalVersion>1.0.11</InformationalVersion>
    <UserSecretsId>dotnet-EPDeskAgent-1001eba0-b591-4af9-a1ea-84aefb4120ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>
</Project>
